export const createorderType= 'CREATEORDERTYPE';
export const deleteorderType= 'DELETEORDERTYPE';
export const fetchInitiatedAndRunningOrderType= 'FETCHINITIATEDANDRUNNINGORDERTYPE';
export const fetchCompletedOrderType= 'FETCHINCOMPLETEDORDERTYPE';
export const activeOrder= "ACTIVEORDER";
export const signinType = "SIGNINTYPE";
export const signupType = "SIGNUPTYPE";
export const signoutType = "SIGNOUTTYPE";
export const showSpinner= "SHOWSPINNER";
export const hideSpinner= "HIDESPINNER";
export const errorLogin= "ERRORLOGIN";
export const errorSignup= "ERRORSIGNUP";
export const updateAuth= "UPDATEAUTH";
export const fetchPublishedPost= "FETCHPUBLISHEDPOST";
export const setActivePost= "SETACTIVEPOST"